import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const satoshi = localFont({
  src: [
    {
      path: "./fonts/satoshi/Satoshi-Regular.ttf",
      weight: "normal",
    },
    {
      path: "./fonts/satoshi/Satoshi-Medium.ttf",
      weight: "500",
    },
    {
      path: "./fonts/satoshi/Satoshi-Bold.ttf",
      weight: "bold",
    },
  ],
  variable: "--font-satoshi",
});

const messapia = localFont({
  src: [
    {
      path: "./fonts/Messapia-Bold.otf",
    },
  ],
  variable: "--font-messapia",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${messapia.variable} ${satoshi.variable} font-sans`}>
        {children}
      </body>
    </html>
  );
}
